# Generated by Django 3.0.6 on 2020-09-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageCrop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('file', models.ImageField(upload_to='images')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
